### ISSUE TITLE
Need example for depth

### ISSUE THREAD

**Issue by shyam573** [nnstreamer/nnstreamer-example#224]
I need support with these two:
1. The main repo claims that the tensor decoder supports depth too. But I do not see an example here. Can you provide an example of a depth model with a suitable tensor decoder mode?

2. Where are the various tensor decoder modes explained? I cannot find it in the documentation.

Thanks.

**Comment by myungjoo** [comment]
1. Yes.. there is no sample apps upstreamed. Because of the similarity of visualization techniques between depth and segmentation, depth can be visualized with https://github.com/nnstreamer/nnstreamer/blob/main/ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c

Note that, in general, you do not need to "decode" in real application. Tensor decoding is only required when you need to visualize for demonstration. If your application actually uses the output data of neural networks, you usually do not decode (convert tensors to "video"), but directly use it with possibly a few post processors.

2. Because tensor decoders are supposed to be implemented by users and attached in plug-and-play manner, we do not have centralized documentation. You will need to look at the GST-doc entries of each decoders (e.g., at the top of the above code.) 

If you want to read documents, not comments of each source file, you may generate documents with doxygen. Then, you will be able to see all upstreamed decoders' documents with PDF readers or web browsers.

**Comment by shyam573** [comment]
Thank you for your reply. It was helpful. I'll try doxygen.
